from main.models.attendances import *
from main.models.child_ratings import *
from main.models.children import *
from main.models.consumed_products import *
from main.models.districts import *
from main.models.groups import *
from main.models.kindergartens import *
from main.models.note_of_health import *
from main.models.payments import *
from main.models.products import *
from main.models.regions import *