# Generated by Django 5.1.6 on 2025-05-19 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='kindergarten_id',
        ),
        migrations.AddField(
            model_name='user',
            name='kindergarten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.kindergarten'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('manager', 'Manager'), ('director', 'Director'), ('nursery', 'Nursery'), ('nurse', 'Nurse'), ('chef', 'Chef'), ('parent', 'Parent')], default=0, max_length=20, verbose_name='Role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='salary_status',
            field=models.BooleanField(default=False, verbose_name='Salary status'),
        ),
    ]
