# Generated by Django 5.2.1 on 2025-05-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin'), ('manager', 'Manager'), ('director', 'Director'), ('nursery', 'Nursery'), ('nurse', 'Nurse'), ('chef', 'Chef'), ('parent', 'Parent')], default='user', max_length=20, null=True, verbose_name='Role'),
        ),
    ]
