# Generated by Django 5.1.6 on 2025-05-19 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth')),
                ('payment_status', models.BooleanField(default=False, verbose_name='Payment status')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Parent ID')),
            ],
            options={
                'verbose_name': 'Child',
                'verbose_name_plural': 'Children',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(verbose_name='Attended')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Administrator ID')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.child', verbose_name='Child ID')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
            },
        ),
        migrations.CreateModel(
            name='ChildRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(verbose_name='Grade')),
                ('comment', models.TextField(verbose_name='Comment')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.child', verbose_name='Child ID')),
                ('nursery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nursery ID')),
            ],
            options={
                'verbose_name': 'Child Rating',
                'verbose_name_plural': 'Child Ratings',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Title')),
                ('number_of_children', models.PositiveIntegerField(verbose_name='Number of children')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('nursery_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nursery ID')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.group', verbose_name='Group ID'),
        ),
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('number_of_children', models.PositiveBigIntegerField(verbose_name='Number of children')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('district_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.district', verbose_name='District')),
            ],
            options={
                'verbose_name': 'Kindergarten',
                'verbose_name_plural': 'Kindergartens',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='kindergarten_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kindergarten', verbose_name='Kindergarten ID'),
        ),
        migrations.CreateModel(
            name='ConsumedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('chef_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Chef ID')),
                ('kindergarten_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kindergarten', verbose_name='Kindergarten ID')),
            ],
            options={
                'verbose_name': 'Consumed Product',
                'verbose_name_plural': 'Consumed Products',
            },
        ),
        migrations.CreateModel(
            name='NoteOfHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.child', verbose_name='Child ID')),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nurse ID')),
            ],
            options={
                'verbose_name': 'Note of Health',
                'verbose_name_plural': 'Note of Health',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('type_of_payment', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=20, verbose_name='Type of Payment')),
                ('month', models.CharField(max_length=50, verbose_name='Month')),
                ('description', models.TextField(verbose_name='Description')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.child', verbose_name='Child ID')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('given_money', models.FloatField(verbose_name='Given money')),
                ('description', models.TextField(verbose_name='Description')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Added at')),
                ('kindergarten_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.kindergarten', verbose_name='Kindergarten ID')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='district',
            name='region_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.region', verbose_name='Region ID'),
        ),
    ]
