# Generated by Django 5.1.6 on 2025-05-23 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kindergarten',
            name='district_id',
        ),
    ]
